# Generated by Django 4.2.11 on 2026-04-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpenhoPagamentoParcial',
            fields=[
                ('id_empenho', models.AutoField(primary_key=True, serialize=False)),
                ('empenho', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField(max_length=200)),
                ('ativo', models.BooleanField(blank=True, default=True)),
            ],
            options={
                'db_table': 'pagamento_parcial_empenho',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoDocumentoPagamentoParcial',
            fields=[
                ('id_tipo_documento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(max_length=20, unique=True)),
                ('ativo', models.BooleanField(blank=True, default=True)),
            ],
            options={
                'verbose_name': 'Tipo de documento',
                'db_table': 'pagamento_parcial_tipo_documento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransacaoPagamentoParcial',
            fields=[
                ('id_transacao', models.AutoField(primary_key=True, serialize=False)),
                ('eh_credito', models.BooleanField(db_column='credito', default=False)),
                ('documento', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField(max_length=50)),
                ('data_lancamento', models.DateField(auto_now=True)),
                ('montante', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Transação',
                'db_table': 'pagamento_parcial_transacao',
                'ordering': ['id_transacao'],
                'managed': False,
            },
        ),
    ]
