# Generated by Django 4.2.11 on 2026-04-13 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpenhoPagamentoParcial',
            fields=[
                ('id_empenho', models.AutoField(primary_key=True, serialize=False)),
                ('empenho', models.CharField(max_length=50, unique=True)),
                ('descricao', models.CharField(max_length=50)),
                ('montante', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('ativo', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumentoPagamentoParcial',
            fields=[
                ('id_tipo_documento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(max_length=20, unique=True)),
                ('ativo', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TransacaoPagamentoParcial',
            fields=[
                ('id_transacao', models.AutoField(primary_key=True, serialize=False)),
                ('credito', models.BooleanField(default=False)),
                ('documento', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField(max_length=50)),
                ('data_lancamento', models.DateField(auto_now=True)),
                ('montante', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ativo', models.BooleanField(blank=True, default=False)),
                ('empenho_pai', models.ForeignKey(db_column='id_empenho', on_delete=django.db.models.deletion.DO_NOTHING, to='partial_payments.empenhopagamentoparcial')),
                ('tipo_documento', models.ForeignKey(db_column='id_tipo_documento', on_delete=django.db.models.deletion.DO_NOTHING, to='partial_payments.tipodocumentopagamentoparcial')),
            ],
        ),
    ]
