services:
  web:
    build: .
    container_name: ngo-ccsh-backend-dev
    environment:
      DJANGO_SETTINGS_MODULE: ngo_ccsh.dev_settings
      DEBUG: "True"
    volumes:
      - ./backend:/home/backend
    ports:
      - "8001:8000"  # 8001 no host, 8000 no container. porta do container é controlada pelo Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    command: >
      sh -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn ngo_ccsh.wsgi:application --bind 0.0.0.0:8000 --reload
      "