name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - python=3.12.*
  - django
  - djangorestframework
  - pandas
  - numpy
  - pip:
      - djangorestframework-simplejwt
      - python-dotenv
      - psycopg2-binary
