CREATE TABLE "usuarios" (
  "id_usuario" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar NOT NULL,
  "password" varchar NOT NULL,
  "email" varchar NOT NULL,
  "administrador" boolean DEFAULT false
);

CREATE TABLE "subunidades" (
  "id_subunidade" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "subunidade" varchar NOT NULL
);

CREATE TABLE "tipos_transacoes" (
  "id_tipo_transacao" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tipo_transacao" varchar NOT NULL
);

CREATE TABLE "finalidades" (
  "id_finalidade" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_tabela_finalidade" integer DEFAULT null,
  "finalidade" varchar NOT NULL
);

CREATE TABLE "tabelas_finalidades" (
  "id_tabela_finalidade" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tabela_finalidade" varchar NOT NULL
);

CREATE TABLE "tipos_documento" (
  "id_tipo_documento" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tipo_documento" varchar NOT NULL
);

CREATE TABLE "status" (
  "id_status" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "status" varchar NOT NULL
);

CREATE TABLE "transacoes" (
  "id_transacao" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_tipo_transacao" integer NOT NULL,
  "id_transacao_pai" integer DEFAULT null,
  "id_finalidade" integer DEFAULT null,
  "id_subunidade_credora" integer DEFAULT null,
  "id_subunidade_executora" integer DEFAULT null,
  "id_usuario" integer NOT NULL,
  "id_status" integer NOT NULL,
  "id_tipo_documento" integer DEFAULT null,
  "descricao" varchar DEFAULT null,
  "montante" decimal(15,2) DEFAULT 0,
  "data_transacao" date DEFAULT (now()),
  "data_operacao" timestamp DEFAULT (now()),
  "data_atualizacao" timestamp DEFAULT (now()),
  "documento" varchar DEFAULT null
);

CREATE TABLE "beneficiarios" (
  "id_beneficiario" integer PRIMARY KEY,
  "nome_beneficiario" varchar,
  "matricula" varchar DEFAULT null
);

CREATE TABLE "bolsas" (
  "id_transacao" integer PRIMARY KEY,
  "id_beneficiario" integer,
  "op_sf" varchar NOT NULL
);

CREATE TABLE "hospedagem" (
  "id_transacao" integer PRIMARY KEY,
  "id_beneficiario" integer,
  "quantidade_diarias" float
);

CREATE TABLE "diarias" (
  "id_transacao" integer PRIMARY KEY,
  "id_beneficiario" integer,
  "local" varchar,
  "quantidade_diarias" float
);

CREATE TABLE "passagens" (
  "id_transacao" integer PRIMARY KEY,
  "id_beneficiario" integer,
  "local_trecho" varchar
);

CREATE TABLE "refeicoes" (
  "id_transacao" integer PRIMARY KEY,
  "id_beneficiario" integer,
  "quantidade" integer
);

CREATE TABLE "manutencao" (
  "id_transacao" integer PRIMARY KEY,
  "setor" varchar
);

CREATE TABLE "grafica" (
  "id_transacao" integer PRIMARY KEY,
  "cnpj_empresa" varchar
);

ALTER TABLE "bolsas" ADD FOREIGN KEY ("id_beneficiario") REFERENCES "beneficiarios" ("id_beneficiario");

ALTER TABLE "hospedagem" ADD FOREIGN KEY ("id_beneficiario") REFERENCES "beneficiarios" ("id_beneficiario");

ALTER TABLE "diarias" ADD FOREIGN KEY ("id_beneficiario") REFERENCES "beneficiarios" ("id_beneficiario");

ALTER TABLE "passagens" ADD FOREIGN KEY ("id_beneficiario") REFERENCES "beneficiarios" ("id_beneficiario");

ALTER TABLE "refeicoes" ADD FOREIGN KEY ("id_beneficiario") REFERENCES "beneficiarios" ("id_beneficiario");

ALTER TABLE "finalidades" ADD FOREIGN KEY ("id_tabela_finalidade") REFERENCES "tabelas_finalidades" ("id_tabela_finalidade");

ALTER TABLE "transacoes" ADD FOREIGN KEY ("id_tipo_documento") REFERENCES "tipos_documento" ("id_tipo_documento");

ALTER TABLE "transacoes" ADD FOREIGN KEY ("id_tipo_transacao") REFERENCES "tipos_transacoes" ("id_tipo_transacao");

ALTER TABLE "transacoes" ADD FOREIGN KEY ("id_transacao_pai") REFERENCES "transacoes" ("id_transacao");

ALTER TABLE "transacoes" ADD FOREIGN KEY ("id_finalidade") REFERENCES "finalidades" ("id_finalidade");

ALTER TABLE "transacoes" ADD FOREIGN KEY ("id_subunidade_credora") REFERENCES "subunidades" ("id_subunidade");

ALTER TABLE "transacoes" ADD FOREIGN KEY ("id_subunidade_executora") REFERENCES "subunidades" ("id_subunidade");

ALTER TABLE "transacoes" ADD FOREIGN KEY ("id_usuario") REFERENCES "usuarios" ("id_usuario");

ALTER TABLE "transacoes" ADD FOREIGN KEY ("id_status") REFERENCES "status" ("id_status");

ALTER TABLE "transacoes" ADD FOREIGN KEY ("id_transacao") REFERENCES "bolsas" ("id_transacao");

ALTER TABLE "transacoes" ADD FOREIGN KEY ("id_transacao") REFERENCES "hospedagem" ("id_transacao");

ALTER TABLE "transacoes" ADD FOREIGN KEY ("id_transacao") REFERENCES "diarias" ("id_transacao");

ALTER TABLE "transacoes" ADD FOREIGN KEY ("id_transacao") REFERENCES "passagens" ("id_transacao");

ALTER TABLE "transacoes" ADD FOREIGN KEY ("id_transacao") REFERENCES "refeicoes" ("id_transacao");

ALTER TABLE "transacoes" ADD FOREIGN KEY ("id_transacao") REFERENCES "manutencao" ("id_transacao");

ALTER TABLE "transacoes" ADD FOREIGN KEY ("id_transacao") REFERENCES "grafica" ("id_transacao");
