SET CURRENT SCHEMA = 'ORCAMENTO';


CREATE TABLE SUBUNIDADES (
  id_subunidade INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subunidade VARCHAR(255) NOT NULL
);

CREATE TABLE NATUREZA_TRANSACAO (
  id_tipo_transacao INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo_transacao varchar(100)  NOT NULL
);

CREATE TABLE TIPO_DESPESA (
  id_tipo_despesa integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo_despesa varchar(100) 
);

CREATE TABLE SUBTIPO_FINALIDADES (
  id_subtipo_finalidade INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subtipo_finalidade varchar(255)  NOT NULL
);

CREATE TABLE FINALIDADES (
  id_finalidade INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_tipo_despesa integer,
  id_subtipo_finalidade integer NOT NULL,
  finalidade varchar(255)  NOT NULL
);



CREATE TABLE TIPOS_DOCUMENTOS (
  id_tipo_documento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo_documento varchar(100)  NOT NULL
);

CREATE TABLE DOCUMENTOS (
  id_documento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_tipo_documento integer NOT NULL,
  id_transacao integer NOT NULL,
  descricao varchar(100)  NOT NULL
);

CREATE TABLE STATUS (
  id_status INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status varchar(100)  NOT NULL
);

CREATE TABLE BENEFICIARIOS (
  id_beneficiario integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome_beneficiario varchar(100)  NOT NULL,
  cpf varchar(14) ,
  matricula varchar(50) 
);

CREATE TABLE TRANSACOES (
  id_transacao INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_tipo_transacao integer NOT NULL,
  id_transacao_pai integer,
  id_finalidade integer,
  id_subunidade_credora integer,
  id_subunidade_executora integer,
  id_usuario integer NOT NULL,
  id_status integer NOT NULL,
  id_beneficiario integer,
  descricao varchar(500) ,
  montante decimal(15,2) DEFAULT 0,
  motivo_modificacao varchar(500) ,
  quantidade FLOAT,
  local_techo varchar(255) ,
  data_lancamento TIMESTAMP DEFAULT CURRENT TIMESTAMP,
  data_modificacao TIMESTAMP DEFAULT CURRENT TIMESTAMP
);



ALTER TABLE FINALIDADES ADD CONSTRAINT fk_finalidades_subtipo  FOREIGN KEY (id_subtipo_finalidade) REFERENCES SUBTIPO_FINALIDADES (id_subtipo_finalidade) ENFORCED  ;



ALTER TABLE DOCUMENTOS ADD CONSTRAINT fk_documentos_tipos_documentos FOREIGN KEY (id_tipo_documento) REFERENCES TIPOS_DOCUMENTOS (id_tipo_documento) ENFORCED ;


ALTER TABLE DOCUMENTOS ADD CONSTRAINT fk_documentos_transacoes FOREIGN KEY (id_transacao) REFERENCES TRANSACOES (id_transacao) ENFORCED ;


ALTER TABLE TRANSACOES ADD CONSTRAINT fk_transacoes_beneficiarios FOREIGN KEY (id_beneficiario) REFERENCES BENEFICIARIOS (id_beneficiario) ENFORCED ;


ALTER TABLE FINALIDADES ADD CONSTRAINT fk_finalidades_tipo_despesa FOREIGN KEY (id_tipo_despesa) REFERENCES TIPO_DESPESA (id_tipo_despesa) ENFORCED ;


ALTER TABLE TRANSACOES ADD CONSTRAINT fk_transacoes_tipo_transacao FOREIGN KEY (id_tipo_transacao) REFERENCES NATUREZA_TRANSACAO (id_tipo_transacao) ENFORCED ;


ALTER TABLE TRANSACOES ADD CONSTRAINT fk_transacoes_transacao_pai FOREIGN KEY (id_transacao_pai) REFERENCES TRANSACOES (id_transacao) ENFORCED ;


ALTER TABLE TRANSACOES ADD CONSTRAINT fk_transacoes_finalidades FOREIGN KEY (id_finalidade) REFERENCES FINALIDADES (id_finalidade) ENFORCED ;


ALTER TABLE TRANSACOES ADD CONSTRAINT fk_transacoes_subunidade_credora FOREIGN KEY (id_subunidade_credora) REFERENCES SUBUNIDADES (id_subunidade) ENFORCED ;


ALTER TABLE TRANSACOES ADD CONSTRAINT fk_transacoes_subunidade_executora FOREIGN KEY (id_subunidade_executora) REFERENCES SUBUNIDADES (id_subunidade) ENFORCED ;


ALTER TABLE TRANSACOES ADD CONSTRAINT fk_transacoes_status FOREIGN KEY (id_status) REFERENCES STATUS (id_status) ENFORCED ; 