SET CURRENT SCHEMA = 'ORCAMENTO';

CREATE TABLE FINALIDADES (
  id_finalidade INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_tipo_despesa integer,
  id_categoria_finalidade integer NOT NULL,
  finalidade varchar(255)  NOT NULL
);

ALTER TABLE FINALIDADES ADD CONSTRAINT fk_finalidades_categoria_finalidade  FOREIGN KEY (id_categoria_finalidade) REFERENCES CATEGORIAS_FINALIDADES (id_categoria_finalidade) ENFORCED;
ALTER TABLE FINALIDADES ADD CONSTRAINT fk_finalidades_tipos_despesa FOREIGN KEY (id_tipo_despesa) REFERENCES TIPOS_DESPESA (id_tipo_despesa) ENFORCED ;