SET CURRENT SCHEMA = 'ORCAMENTO';

CREATE TABLE TRANSACOES (
  id_transacao INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_tipo_transacao integer NOT NULL,
  id_transacao_pai integer,
  id_finalidade integer,
  id_subunidade_credora integer,
  id_subunidade_executora integer,
  id_usuario integer NOT NULL,
  id_status integer NOT NULL,
  id_beneficiario integer,
  descricao varchar(500) ,
  montante decimal(15,2) DEFAULT 0,
  motivo_modificacao varchar(500) ,
  quantidade FLOAT,
  local_techo varchar(255) ,
  data_lancamento TIMESTAMP DEFAULT CURRENT TIMESTAMP,
  data_modificacao TIMESTAMP DEFAULT CURRENT TIMESTAMP
);

ALTER TABLE TRANSACOES ADD CONSTRAINT fk_transacoes_beneficiarios FOREIGN KEY (id_beneficiario) REFERENCES BENEFICIARIOS (id_beneficiario) ENFORCED ;
ALTER TABLE TRANSACOES ADD CONSTRAINT fk_transacoes_tipos_transacoes FOREIGN KEY (id_tipo_transacao) REFERENCES TIPOS_TRANSACOES (id_tipo_transacao) ENFORCED ;
ALTER TABLE TRANSACOES ADD CONSTRAINT fk_transacoes_transacao_pai FOREIGN KEY (id_transacao_pai) REFERENCES TRANSACOES (id_transacao) ENFORCED ;
ALTER TABLE TRANSACOES ADD CONSTRAINT fk_transacoes_finalidades FOREIGN KEY (id_finalidade) REFERENCES FINALIDADES (id_finalidade) ENFORCED ;
ALTER TABLE TRANSACOES ADD CONSTRAINT fk_transacoes_subunidade_credora FOREIGN KEY (id_subunidade_credora) REFERENCES SUBUNIDADES (id_subunidade) ENFORCED ;
ALTER TABLE TRANSACOES ADD CONSTRAINT fk_transacoes_subunidade_executora FOREIGN KEY (id_subunidade_executora) REFERENCES SUBUNIDADES (id_subunidade) ENFORCED ;
ALTER TABLE TRANSACOES ADD CONSTRAINT fk_transacoes_status FOREIGN KEY (id_status) REFERENCES STATUS (id_status) ENFORCED ;