"""
Django settings for ngo_ccsh project.

Generated by 'django-admin startproject' using Django 6.0.1.
"""

import os
import sys
import json

import platform
from pathlib import Path
from datetime import timedelta
# from dotenv import load_dotenv

from django.core.exceptions import ImproperlyConfigured


def get_secret(attribute):
    """
    Retorna uma configuração armazenada em um arquivo.
    """

    with open(os.path.join(BASE_DIR, '..', 'instance', 'database_credentials.json')) as read_file:
        secrets = json.load(read_file)

    try:
        return secrets[attribute]
    except KeyError:
        raise ImproperlyConfigured(
            f"Não foi encontrado o atributo {attribute} no arquivo "
            f"{os.path.abspath(os.path.join(BASE_DIR, '..', 'instance', 'database_credentials.json'))}"
        )

# TODO remover
# # --- CONFIGURAÇÃO DE DLL PARA IBM DB2 (WINDOWS) ---
# if platform.system() == "Windows":
#     # Caminho exato que você encontrou
#     IBM_DB_DLL_PATH = r"C:\Users\Leandro Galbarino\miniconda3\envs\my_env\Lib\site-packages\clidriver\bin"
#
#     if os.path.exists(IBM_DB_DLL_PATH):
#         # Isso ensina o Python 3.12 a procurar as DLLs nesta pasta
#         os.add_dll_directory(IBM_DB_DLL_PATH)
#     else:
#         # Tenta localizar dinamicamente caso o nome do ambiente mude
#         print(f"Aviso: Pasta de DLLs da IBM não encontrada em {IBM_DB_DLL_PATH}")
# # --------------------------------------------------

# load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "fallback-inseguro-apenas-dev")
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    "users",  # aplicação própria
    "transactions",  # aplicação própria
    "partial_payments",  # aplicação própria
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "ngo_ccsh.urls"

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAuthenticated"],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}

CORS_ALLOW_ALL_ORIGINS = True

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
    # "TEMPLATES",
]

WSGI_APPLICATION = "ngo_ccsh.wsgi.application"

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        "NAME": 'BEE',
        "ENGINE": 'ibm_db_django',
        "DATABASE": get_secret('database'),
        "HOST": get_secret('host'),
        "PORT": get_secret('port'),
        "USER": get_secret('user'),
        "PASSWORD": get_secret('password'),
        "OPTIONS": {
            'dsn': f"DATABASE={get_secret('database')};HOSTNAME={get_secret('host')};"
                   f"PORT={get_secret('port')};PROTOCOL=TCPIP;"
        },
        'PCONNECT': True,
    },
    'local_sqlite': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'prod.sqlite3',
    },
}

DATABASE_ROUTERS = ['app.db_routers.LocalAppsRouter']

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators
AUTH_USER_MODEL = "users.CustomUser"

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = False  # precisa ser falso para usar ibm db2

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / 'static']


EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv("EMAIL_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_PASSWORD")
DEFAULT_FROM_EMAIL = "Webmaster <leandrokise753@gmail.com>"
