"""
Django settings for ngo_ccsh project.

Generated by 'django-admin startproject' using Django 6.0.1.
"""

import os
import json

from pathlib import Path
from datetime import timedelta

import django
from django.apps import apps
from django.db import connection

from django.core.exceptions import ImproperlyConfigured

BASE_DIR = Path(__file__).resolve().parent.parent


SECRETS_FILE = os.path.abspath(
    os.path.join(BASE_DIR, '..', 'instance', 'database_credentials.json')
)

def load_secrets():
    try:
        with open(SECRETS_FILE) as f:
            return json.load(f)
    except FileNotFoundError:
        return {}

SECRETS = load_secrets()

def get_secret(key):
    """
    Tenta ler parâmetros nessa ordem:
    1. Parâmetros pela linha de comando
    2. Arquivo JSON em SECRETS_FILE
    3. Parâmetro padrão
    """

    # parâmetro pela CLI
    value = os.getenv(key)
    if value is not None:
        return value

    # arquivo JSON
    if key in SECRETS:
        return SECRETS[key]

    raise ImproperlyConfigured(
        f"Não foi encontrado o atributo '{key}' no CLI nem no arquivo {SECRETS_FILE}"
    )

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "fallback-inseguro-apenas-dev")
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    "users",  # aplicação própria
    "transactions",  # aplicação própria
    "partial_payments",  # aplicação própria
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "ngo_ccsh.urls"

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAuthenticated"],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        'rest_framework.authentication.SessionAuthentication',
    ],
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}

CORS_ALLOW_ALL_ORIGINS = True

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
    # "TEMPLATES",
]

WSGI_APPLICATION = "ngo_ccsh.wsgi.application"

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        "NAME": 'BEE',
        "ENGINE": 'ibm_db_django',
        "DATABASE": get_secret('DB_DATABASE'),
        "HOST": get_secret('DB_HOST'),
        "PORT": get_secret('DB_PORT'),
        "USER": get_secret('DB_USERNAME'),
        "PASSWORD": get_secret('DB_PASSWORD'),
        "OPTIONS": {
            'dsn': f"DATABASE={get_secret('DB_DATABASE')};"
                   f"HOSTNAME={get_secret('DB_HOST')};"
                   f"PORT={get_secret('DB_PORT')};"
                   f"PROTOCOL=TCPIP;"
                   f"CURRENTSCHEMA={get_secret('DB_SCHEMA')};"
        },
        'PCONNECT': True,
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators
AUTH_USER_MODEL = "users.Usuario"

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = False  # precisa ser falso para usar ibm db2

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / 'static']


EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv("EMAIL_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_PASSWORD")
DEFAULT_FROM_EMAIL = "Webmaster <leandrokise753@gmail.com>"


def force_create_unmanaged_models():
    """
    Cria tabelas para modelos com managed=False (útil em dev com SQLite).
    """
    django.setup()
    for model in apps.get_models():
        if not model._meta.managed:
            model._meta.managed = True
            with connection.schema_editor() as schema_editor:
                try:
                    schema_editor.create_model(model)
                    print(f'  [OK] Modelo criado: {model.__name__}')
                except Exception as e:
                    print(f'[WARN] Não foi possível criar o modelo {model.__name__}: {e}')