"""
Django settings for ngo_ccsh project.

Generated by 'django-admin startproject' using Django 6.0.1.
"""

from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv
import os
import platform
import sys

from pathlib import Path

# --- CONFIGURAÇÃO DE DLL PARA IBM DB2 (WINDOWS) ---
if platform.system() == "Windows":
    # Caminho exato que você encontrou
    IBM_DB_DLL_PATH = r"C:\Users\Leandro Galbarino\miniconda3\envs\my_env\Lib\site-packages\clidriver\bin"

    if os.path.exists(IBM_DB_DLL_PATH):
        # Isso ensina o Python 3.12 a procurar as DLLs nesta pasta
        os.add_dll_directory(IBM_DB_DLL_PATH)
    else:
        # Tenta localizar dinamicamente caso o nome do ambiente mude
        print(f"Aviso: Pasta de DLLs da IBM não encontrada em {IBM_DB_DLL_PATH}")
# --------------------------------------------------

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "fallback-inseguro-apenas-dev")
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt",
    "users",
    "transactions",
    "partial_payments",
]


REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAuthenticated"],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "ngo_ccsh.urls"

CORS_ALLOW_ALL_ORIGINS = True

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
    # "TEMPLATES",
]

WSGI_APPLICATION = "ngo_ccsh.wsgi.application"
USE_TZ = False

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if not DEBUG:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    # Produção/Homologação (IBM Db2 - CCSH)
    # Pegando as variáveis do seu .env
    db_name = os.getenv("database")
    db_host = os.getenv("host")
    db_port = os.getenv("port")
    db_user = os.getenv("user")
    db_pass = os.getenv("password")

    DATABASES = {
        "default": {
            "ENGINE": "ibm_db_django",
            "NAME": "BEE",
            "USER": db_user,
            "PASSWORD": db_pass,
            "HOST": db_host,
            "PORT": db_port,
            "PCONNECT": True,
            "OPTIONS": {
                # O segredo é colocar o CURRENTSCHEMA aqui dentro do DSN
                "dsn": (
                    f"DATABASE={db_name};"
                    f"HOSTNAME={db_host};"
                    f"PORT={db_port};"
                    f"PROTOCOL=TCPIP;"
                    f"UID={db_user};"
                    f"PWD={db_pass};"
                    f"CURRENTSCHEMA=ORCAMENTO;"
                ),
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators
AUTH_USER_MODEL = "users.CustomUser"

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"


EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv("EMAIL_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_PASSWORD")
DEFAULT_FROM_EMAIL = "Webmaster <leandrokise753@gmail.com>"
