CREATE TABLE ORCAMENTO.DOCUMENTOS (
  id_documento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_tipo_documento integer NOT NULL,
  id_transacao integer NOT NULL,
  descricao varchar(100)  NOT NULL
);

ALTER TABLE ORCAMENTO.DOCUMENTOS ADD CONSTRAINT fk_documentos_tipos_documentoS FOREIGN KEY (id_tipo_documento) REFERENCES TIPOS_DOCUMENTOS (id_tipo_documento) ENFORCED ;
ALTER TABLE ORCAMENTO.DOCUMENTOS ADD CONSTRAINT fk_documentos_transacoes FOREIGN KEY (id_transacao) REFERENCES TRANSACOES (id_transacao) ENFORCED ;