CREATE TABLE ORCAMENTO.BENEFICIARIOS (
  id_beneficiario integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome_beneficiario varchar(100)  NOT NULL,
  cpf varchar(14) ,
  matricula varchar(50)
);