CREATE TABLE ORCAMENTO.CENTROS (
    ID_CENTRO_INTERNO INTEGER NOT NULL PRIMARY KEY,
    ID_CENTRO_SIE INTEGER DEFAULT NULL,
    NOME_CENTRO VARCHAR(256) NOT NULL,
    SIGLA_CENTRO VARCHAR(16) NOT NULL UNIQUE,
    COD_ESTRUTURADO VARCHAR(15) NULL
);

comment on table orcamento.centros is 'Tabela de Centros Internos, incluindo centros do SIE.';