CREATE TABLE ORCAMENTO.EMPENHOS (
    ID_EMPENHO INTEGER NOT NULL PRIMARY KEY,
    NUMERO_EMPENHO VARCHAR(32) NOT NULL,
    NUMERO_PEN VARCHAR(32) NOT NULL,
    ID_FINALIDADE INTEGER NOT NULL REFERENCES ORCAMENTO.FINALIDADES(ID_FINALIDADE),
    DATA_LANCAMENTO TIMESTAMP NOT NULL
);

COMMENT ON table ORCAMENTO.EMPENHOS IS 'Tabela que armazena informações sobre os empenhos, incluindo número do empenho, número do PEN, finalidade associada e data de lançamento.';