CREATE TABLE ORCAMENTO.FINALIDADES (
    id_finalidade INTEGER NOT NULL PRIMARY KEY,
    ID_NATUREZA_FINALIDADE INTEGER NOT NULL REFERENCES ORCAMENTO.NATUREZAS_FINALIDADES (id_natureza_finalidade),
    ID_GRUPO_FINALIDADE INTEGER DEFAULT NULL REFERENCES ORCAMENTO.GRUPOS_FINALIDADES (id_grupo_finalidade),
    finalidade varchar(512) NOT NULL,
    ATIVO BOOLEAN DEFAULT TRUE
);

COMMENT on table orcamento.finalidades is 'Finalidades orçamentárias';