CREATE TABLE ORCAMENTO.NATUREZAS_FINALIDADES (
    ID_NATUREZA_FINALIDADE INTEGER PRIMARY KEY,
    NATUREZA_FINALIDADE VARCHAR(128) NOT NULL,
    ATIVO BOOLEAN DEFAULT TRUE
);

comment on table ORCAMENTO.NATUREZAS_FINALIDADES is 'Naturezas de finalidades orçamentárias';