CREATE TABLE ORCAMENTO.PESSOAS (
    ID_PESSOA_INTERNA INTEGER NOT NULL PRIMARY KEY,
    ID_PESSOA_SIE INTEGER DEFAULT NULL,
    NOME_PESSOA VARCHAR(256) NOT NULL,
    CPF VARCHAR(11) NOT NULL,
    RG VARCHAR(11) NOT NULL
);

comment on table ORCAMENTO.PESSOAS is 'Tabela com pessoas internas da aplicação. Possui também pessoas do SIE.';