CREATE TABLE orcamento.PESSOAS_EXTERNAS (
    ID_PESSOA_EXTERNA PRIMARY KEY,
    NOME_PESSOA VARCHAR(256) NOT NULL,
    CPF VARCHAR(11) NOT NULL UNIQUE,
    RG VARCHAR(11) NOT NULL UNIQUE,
    EMAIL VARCHAR(32) DEFAULT NULL,
    TELEFONE VARCHAR(16) DEFAULT NULL
);