CREATE TABLE ORCAMENTO.UNIDADES (
    ID_UNIDADE_INTERNA INTEGER NOT NULL PRIMARY KEY,
    ID_UNIDADE_SIE INTEGER DEFAULT NULL,
    NOME_UNIDADE VARCHAR(256) NOT NULL,
    COD_ESTRUTURADO VARCHAR(15) NOT NULL,
    ID_CENTRO_INTERNO INTEGER NOT NULL,
    ID_TIPO_UNIDADE INTEGER NOT NULL,
    ID_SITUACAO_UNIDADE INTEGER NOT NULL
);

comment on table orcamento.UNIDADES is 'Tabela de Unidades Internas, incluindo unidades do SIE.';