CREATE TABLE ORCAMENTO.USUARIOS (
    ID INTEGER NOT NULL PRIMARY KEY,
    CPF VARCHAR(11) NOT NULL UNIQUE,
    EMAIL VARCHAR(64) NOT NULL UNIQUE,
    IS_ACTIVE BOOLEAN DEFAULT FALSE,
    IS_STAFF BOOLEAN DEFAULT FALSE,
    IS_SUPERUSER BOOLEAN DEFAULT FALSE,
    CREATED_AT DATE NOT NULL,
    ID_PESSOA INTEGER NOT NULL
);

comment on table orcamento.usuarios is 'Usuários da aplicação financeira.';