CREATE TABLE USUARIOS (
    ID INTEGER PRIMARY KEY,
    CPF VARCHAR(11) NOT NULL UNIQUE,
    EMAIL VARCHAR(64) NOT NULL UNIQUE,
    IS_ACTIVE BOOLEAN DEFAULT FALSE,
    IS_STAFF BOOLEAN DEFAULT FALSE,
    IS_SUPERUSER BOOLEAN DEFAULT FALSE,
    CREATED_AT DATE NOT NULL,
    ID_PESSOA INTEGER NOT NULL REFERENCES PESSOAS(ID_PESSOA)
);