# Generated by Django 6.0.1 on 2026-02-05 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiarios',
            fields=[
                ('id_beneficiario', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_beneficiario', models.CharField(blank=True, null=True)),
                ('matricula', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'beneficiarios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Transacoes',
            fields=[
                ('id_transacao', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, null=True)),
                ('montante', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('documento', models.CharField(blank=True, null=True)),
                ('data_referencia', models.DateField(blank=True, null=True)),
                ('data_lancamento', models.DateTimeField(blank=True, null=True)),
                ('data_atualizacao', models.DateTimeField(blank=True, null=True)),
                ('id_transacao_pai', models.ForeignKey(blank=True, db_column='id_transacao_pai', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transactions.transacoes')),
            ],
            options={
                'db_table': 'transacoes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Finalidades',
            fields=[
                ('id_finalidade', models.AutoField(primary_key=True, serialize=False)),
                ('finalidade', models.CharField()),
            ],
            options={
                'db_table': 'finalidades',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id_status', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField()),
            ],
            options={
                'db_table': 'status',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Subunidades',
            fields=[
                ('id_subunidade', models.AutoField(primary_key=True, serialize=False)),
                ('subunidade', models.CharField()),
            ],
            options={
                'db_table': 'subunidades',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TabelasFinalidades',
            fields=[
                ('id_tabela_finalidade', models.AutoField(primary_key=True, serialize=False)),
                ('tabela_finalidade', models.CharField()),
            ],
            options={
                'db_table': 'tabelas_finalidades',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoDespesa',
            fields=[
                ('id_tipo_despesa', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_despesa', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipo_despesa',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TiposDocumento',
            fields=[
                ('id_tipo_documento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField()),
            ],
            options={
                'db_table': 'tipos_documento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TiposTransacoes',
            fields=[
                ('id_tipo_transacao', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_transacao', models.CharField()),
            ],
            options={
                'db_table': 'tipos_transacoes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Bolsas',
            fields=[
                ('id_transacao', models.OneToOneField(db_column='id_transacao', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='transactions.transacoes')),
                ('op_sf', models.CharField()),
            ],
            options={
                'db_table': 'bolsas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Diarias',
            fields=[
                ('id_transacao', models.OneToOneField(db_column='id_transacao', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='transactions.transacoes')),
                ('local', models.CharField(blank=True, null=True)),
                ('quantidade_diarias', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'diarias',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Empenho',
            fields=[
                ('id_transacao', models.OneToOneField(db_column='id_transacao', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='transactions.transacoes')),
                ('empenho_sie', models.CharField(blank=True, null=True)),
                ('empenho_siafe', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'empenho',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Grafica',
            fields=[
                ('id_transacao', models.OneToOneField(db_column='id_transacao', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='transactions.transacoes')),
                ('cnpj_empresa', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'grafica',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Hospedagem',
            fields=[
                ('id_transacao', models.OneToOneField(db_column='id_transacao', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='transactions.transacoes')),
                ('quantidade_diarias', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hospedagem',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id_transacao', models.OneToOneField(db_column='id_transacao', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='transactions.transacoes')),
                ('setor', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'manutencao',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Passagens',
            fields=[
                ('id_transacao', models.OneToOneField(db_column='id_transacao', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='transactions.transacoes')),
                ('trecho', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'passagens',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Refeicoes',
            fields=[
                ('id_transacao', models.OneToOneField(db_column='id_transacao', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='transactions.transacoes')),
                ('quantidade', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'refeicoes',
                'managed': True,
            },
        ),
    ]
