# Generated by Django 4.2.11 on 2026-03-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiarios',
            fields=[
                ('id_beneficiario', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_beneficiario', models.CharField(max_length=100)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('matricula', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'beneficiarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id_documento', models.IntegerField(primary_key=True, serialize=False)),
                ('id_tipo_documento', models.IntegerField()),
                ('descricao', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'documentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Finalidades',
            fields=[
                ('id_finalidade', models.IntegerField(primary_key=True, serialize=False)),
                ('finalidade', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'finalidades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NaturezaTransacao',
            fields=[
                ('id_tipo_transacao', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_transacao', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'natureza_transacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id_status', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubtipoFinalidades',
            fields=[
                ('id_subtipo_finalidade', models.IntegerField(primary_key=True, serialize=False)),
                ('subtipo_finalidade', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'subtipo_finalidades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subunidades',
            fields=[
                ('id_subunidade', models.IntegerField(primary_key=True, serialize=False)),
                ('subunidade', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'subunidades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoDespesa',
            fields=[
                ('id_tipo_despesa', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_despesa', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tipo_despesa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiposDocumentos',
            fields=[
                ('id_tipo_documento', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipos_documentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transacoes',
            fields=[
                ('id_transacao', models.IntegerField(primary_key=True, serialize=False)),
                ('id_usuario', models.IntegerField()),
                ('descricao', models.CharField(blank=True, max_length=500, null=True)),
                ('montante', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('motivo_modificacao', models.CharField(blank=True, max_length=500, null=True)),
                ('quantidade', models.FloatField(blank=True, null=True)),
                ('local_techo', models.CharField(blank=True, max_length=255, null=True)),
                ('data_lancamento', models.DateTimeField(blank=True, null=True)),
                ('data_modificacao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transacoes',
                'managed': False,
            },
        ),
    ]
