# Generated by Django 5.2.8 on 2026-02-09 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transacoes',
            name='usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transacoes',
            name='finalidade',
            field=models.ForeignKey(blank=True, db_column='id_finalidade', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transactions.finalidades'),
        ),
        migrations.AddField(
            model_name='transacoes',
            name='status',
            field=models.ForeignKey(db_column='id_status', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transactions.status'),
        ),
        migrations.AddField(
            model_name='transacoes',
            name='subunidade_credora',
            field=models.ForeignKey(blank=True, db_column='id_subunidade_credora', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transactions.subunidades'),
        ),
        migrations.AddField(
            model_name='transacoes',
            name='subunidade_executora',
            field=models.ForeignKey(blank=True, db_column='id_subunidade_executora', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transacoes_id_subunidade_executora_set', to='transactions.subunidades'),
        ),
        migrations.AddField(
            model_name='finalidades',
            name='id_tabela_finalidade',
            field=models.ForeignKey(blank=True, db_column='id_tabela_finalidade', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transactions.tabelasfinalidades'),
        ),
        migrations.AddField(
            model_name='finalidades',
            name='id_tipo_despesa',
            field=models.ForeignKey(blank=True, db_column='id_tipo_despesa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transactions.tipodespesa'),
        ),
        migrations.AddField(
            model_name='transacoes',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, db_column='id_tipo_documento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transactions.tiposdocumento'),
        ),
        migrations.AddField(
            model_name='transacoes',
            name='tipo_transacao',
            field=models.ForeignKey(db_column='id_tipo_transacao', on_delete=django.db.models.deletion.DO_NOTHING, to='transactions.tipostransacoes'),
        ),
        migrations.AddField(
            model_name='bolsas',
            name='id_beneficiario',
            field=models.ForeignKey(blank=True, db_column='id_beneficiario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transactions.beneficiarios'),
        ),
        migrations.AddField(
            model_name='diarias',
            name='id_beneficiario',
            field=models.ForeignKey(blank=True, db_column='id_beneficiario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transactions.beneficiarios'),
        ),
        migrations.AddField(
            model_name='hospedagem',
            name='id_beneficiario',
            field=models.ForeignKey(blank=True, db_column='id_beneficiario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transactions.beneficiarios'),
        ),
        migrations.AddField(
            model_name='passagens',
            name='id_beneficiario',
            field=models.ForeignKey(blank=True, db_column='id_beneficiario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transactions.beneficiarios'),
        ),
        migrations.AddField(
            model_name='refeicoes',
            name='id_beneficiario',
            field=models.ForeignKey(blank=True, db_column='id_beneficiario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transactions.beneficiarios'),
        ),
    ]
