# Generated by Django 4.2.11 on 2026-04-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id_beneficiario', models.AutoField(primary_key=True, serialize=False)),
                ('nome_beneficiario', models.CharField(max_length=100)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('matricula', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'beneficiarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoriaFinalidade',
            fields=[
                ('id_categoria_finalidade', models.AutoField(primary_key=True, serialize=False)),
                ('categoria_finalidade', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'categorias_finalidade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'documentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Finalidade',
            fields=[
                ('id_finalidade', models.AutoField(primary_key=True, serialize=False)),
                ('finalidade', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'finalidades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subunidade',
            fields=[
                ('id_subunidade', models.AutoField(primary_key=True, serialize=False)),
                ('subunidade', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'subunidades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id_tipo_documento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipos_documento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoTransacao',
            fields=[
                ('id_tipo_transacao', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_transacao', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipos_transacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id_transacao', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.IntegerField()),
                ('descricao', models.CharField(blank=True, max_length=500, null=True)),
                ('montante', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('motivo_modificacao', models.CharField(blank=True, max_length=500, null=True)),
                ('quantidade', models.FloatField(blank=True, null=True)),
                ('local_techo', models.CharField(blank=True, max_length=255, null=True)),
                ('data_lancamento', models.DateTimeField(blank=True, null=True)),
                ('data_modificacao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transacoes',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Beneficiarios',
        ),
        migrations.DeleteModel(
            name='Documentos',
        ),
        migrations.DeleteModel(
            name='Finalidades',
        ),
        migrations.DeleteModel(
            name='NaturezaTransacao',
        ),
        migrations.DeleteModel(
            name='SubtipoFinalidades',
        ),
        migrations.DeleteModel(
            name='Subunidades',
        ),
        migrations.DeleteModel(
            name='TiposDocumentos',
        ),
        migrations.DeleteModel(
            name='Transacoes',
        ),
        migrations.AlterModelTable(
            name='tipodespesa',
            table='tipos_despesa',
        ),
    ]
