name: CI/CD

on:
  push:
    branches:
      - dev
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t ngo-ccsh-backend .

      - name: Run tests inside container
        run: |
          docker run \
            -e DJANGO_SETTINGS_MODULE=ngo_ccsh.test_settings \
            ngo-ccsh-backend \
            python manage.py test

  deploy:
    needs: test
    runs-on: self-hosted

    # faz deploy apenas se for a branch main
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy on server
        run: |
          cd /var/www/ngo-ccsh-backend
          git pull origin main
          
          docker compose up -d --build
          docker compose run --rm web python manage.py migrate
