name: CI/CD

on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t ngo-ccsh-backend .

      - name: Run tests inside container
        run: |
          docker run \
            -e DJANGO_SETTINGS_MODULE=ngo_ccsh.test_settings \
            -e DJANGO_SECRET_KEY=any-random-secret-key-for-testing \
            -e JWT_SIGNING_KEY=any-random-secret-key-for-testing \
            ngo-ccsh-backend \
            python manage.py test
