name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t ngo-ccsh-backend .

      - name: Criar arquivo .env para os testes
        run: |
          cat <<EOF > .env
          DEBUG=False
          APP_FULL_NAME=Sistema de Gerenciamento de Gastos Acadêmicos da UFSM
          APP_SHORT_NAME=SIGGA
          FRONTEND_URL=http://localhost:5173
          EMAIL_HOST_USER=${{ secrets.TEST_EMAIL_HOST_USER }}
          EMAIL_HOST_PASSWORD=${{ secrets.TEST_EMAIL_HOST_PASSWORD }}
          DEFAULT_FROM_EMAIL=Núcleo de Gestão Orçamentária <no-reply@ufsm.br>
          DJANGO_SECRET_KEY=${{ secrets.TEST_DJANGO_SECRET_KEY }}
          JWT_SIGNING_KEY=${{ secrets.TEST_JWT_SIGNING_KEY }}
          EOF

      - name: Run tests inside container
        run: |
          docker run \
            -e DJANGO_SETTINGS_MODULE=ngo_ccsh.test_settings \
            --env-file .env \
            ngo-ccsh-backend \
            python manage.py test

      - name: Remover .env
        if: always()
        run: rm -f .env

  deploy:
    needs: test
    runs-on: self-hosted

    steps:
      - name: Deploy on server
        run: |
          cd /home/coplin/ngo-ccsh-backend
          git pull origin main

          docker compose build

          docker compose run --rm web python manage.py migrate
          docker compose run --rm web python manage.py collectstatic --noinput

          docker compose up -d